export const CATEGORIES = [
  "All",
  "Sports & Fitness",
  "Music",
  "Tech",
  "Arts & Crafts",
  "Food",
  "Languages",
  "Other",
];

export const SKILLS = [
  // Sports & Fitness
  { icon: "🧘", label: "Yoga", category: "Sports & Fitness" },
  { icon: "🧘", label: "Pilates", category: "Sports & Fitness" },
  { icon: "🥊", label: "Boxing", category: "Sports & Fitness" },
  { icon: "🥋", label: "Muay Thai", category: "Sports & Fitness" },
  { icon: "🥋", label: "Brazilian Jiu-Jitsu", category: "Sports & Fitness" },
  { icon: "🥋", label: "Wrestling", category: "Sports & Fitness" },
  { icon: "🧗", label: "Rock Climbing", category: "Sports & Fitness" },
  { icon: "🏊", label: "Swimming", category: "Sports & Fitness" },
  { icon: "🏃", label: "Running", category: "Sports & Fitness" },
  { icon: "🚴", label: "Cycling", category: "Sports & Fitness" },
  { icon: "🏋️", label: "Weightlifting", category: "Sports & Fitness" },
  { icon: "🏋️", label: "CrossFit", category: "Sports & Fitness" },
  { icon: "🤸", label: "Gymnastics", category: "Sports & Fitness" },
  { icon: "🥋", label: "Martial Arts", category: "Sports & Fitness" },
  { icon: "🎾", label: "Tennis", category: "Sports & Fitness" },
  { icon: "🎾", label: "Squash", category: "Sports & Fitness" },
  { icon: "🏸", label: "Badminton", category: "Sports & Fitness" },
  { icon: "🏓", label: "Pickleball", category: "Sports & Fitness" },
  { icon: "⛳", label: "Golf", category: "Sports & Fitness" },
  { icon: "⚽", label: "Soccer", category: "Sports & Fitness" },
  { icon: "🏀", label: "Basketball", category: "Sports & Fitness" },
  { icon: "🏐", label: "Volleyball", category: "Sports & Fitness" },
  { icon: "🚣", label: "Rowing", category: "Sports & Fitness" },
  { icon: "🛹", label: "Skateboarding", category: "Sports & Fitness" },
  { icon: "💃", label: "Salsa", category: "Sports & Fitness" },
  { icon: "🕺", label: "Hip Hop Dance", category: "Sports & Fitness" },
  { icon: "💃", label: "Ballroom Dancing", category: "Sports & Fitness" },
  { icon: "🩰", label: "Ballet", category: "Sports & Fitness" },
  { icon: "🏃", label: "Parkour", category: "Sports & Fitness" },
  { icon: "💪", label: "Calisthenics", category: "Sports & Fitness" },
  { icon: "🧘", label: "Stretching & Mobility", category: "Sports & Fitness" },
  { icon: "🤺", label: "Fencing", category: "Sports & Fitness" },
  { icon: "🏹", label: "Archery", category: "Sports & Fitness" },

  // Music
  { icon: "🎸", label: "Acoustic Guitar", category: "Music" },
  { icon: "🎸", label: "Electric Guitar", category: "Music" },
  { icon: "🎸", label: "Bass Guitar", category: "Music" },
  { icon: "🎹", label: "Piano", category: "Music" },
  { icon: "🥁", label: "Drums", category: "Music" },
  { icon: "🎻", label: "Violin", category: "Music" },
  { icon: "🎻", label: "Viola", category: "Music" },
  { icon: "🎻", label: "Cello", category: "Music" },
  { icon: "🎺", label: "Trumpet", category: "Music" },
  { icon: "🎷", label: "Saxophone", category: "Music" },
  { icon: "🎵", label: "Flute", category: "Music" },
  { icon: "🎵", label: "Clarinet", category: "Music" },
  { icon: "🎵", label: "Trombone", category: "Music" },
  { icon: "🪕", label: "Ukulele", category: "Music" },
  { icon: "🪕", label: "Banjo", category: "Music" },
  { icon: "🪕", label: "Mandolin", category: "Music" },
  { icon: "🎤", label: "Classical Singing", category: "Music" },
  { icon: "🎤", label: "Pop Singing", category: "Music" },
  { icon: "🎤", label: "Beatboxing", category: "Music" },
  { icon: "🎛️", label: "Music Production", category: "Music" },
  { icon: "🎛️", label: "DJing", category: "Music" },
  { icon: "🎼", label: "Music Theory", category: "Music" },
  { icon: "✍️", label: "Songwriting", category: "Music" },
  { icon: "🎚️", label: "Sound Engineering", category: "Music" },

  // Tech
  { icon: "🐍", label: "Python", category: "Tech" },
  { icon: "🌐", label: "JavaScript", category: "Tech" },
  { icon: "⚛️", label: "React", category: "Tech" },
  { icon: "🟢", label: "Node.js", category: "Tech" },
  { icon: "📱", label: "iOS Development", category: "Tech" },
  { icon: "📱", label: "Android Development", category: "Tech" },
  { icon: "🗄️", label: "SQL", category: "Tech" },
  { icon: "📊", label: "Data Science", category: "Tech" },
  { icon: "🤖", label: "Machine Learning", category: "Tech" },
  { icon: "🔒", label: "Cybersecurity", category: "Tech" },
  { icon: "🎨", label: "Web Design", category: "Tech" },
  { icon: "🖥️", label: "UX/UI Design", category: "Tech" },
  { icon: "⚙️", label: "DevOps", category: "Tech" },
  { icon: "🎮", label: "Game Development", category: "Tech" },
  { icon: "🎬", label: "Video Editing", category: "Tech" },
  { icon: "✨", label: "Motion Graphics", category: "Tech" },
  { icon: "🖨️", label: "3D Printing", category: "Tech" },
  { icon: "💬", label: "Prompt Engineering", category: "Tech" },

  // Arts & Crafts
  { icon: "✏️", label: "Drawing", category: "Arts & Crafts" },
  { icon: "🖌️", label: "Oil Painting", category: "Arts & Crafts" },
  { icon: "🎨", label: "Watercolor", category: "Arts & Crafts" },
  { icon: "🎨", label: "Acrylic Painting", category: "Arts & Crafts" },
  { icon: "✏️", label: "Illustration", category: "Arts & Crafts" },
  { icon: "🖨️", label: "Printmaking", category: "Arts & Crafts" },
  { icon: "🗿", label: "Sculpture", category: "Arts & Crafts" },
  { icon: "🏺", label: "Pottery & Ceramics", category: "Arts & Crafts" },
  { icon: "🧶", label: "Knitting", category: "Arts & Crafts" },
  { icon: "🧶", label: "Crocheting", category: "Arts & Crafts" },
  { icon: "🧵", label: "Sewing", category: "Arts & Crafts" },
  { icon: "🧵", label: "Embroidery", category: "Arts & Crafts" },
  { icon: "💍", label: "Jewelry Making", category: "Arts & Crafts" },
  { icon: "👜", label: "Leatherworking", category: "Arts & Crafts" },
  { icon: "🪚", label: "Woodworking", category: "Arts & Crafts" },
  { icon: "✒️", label: "Calligraphy", category: "Arts & Crafts" },
  { icon: "🖨️", label: "Screen Printing", category: "Arts & Crafts" },
  { icon: "📷", label: "Photography", category: "Arts & Crafts" },
  { icon: "📷", label: "Film Photography", category: "Arts & Crafts" },
  { icon: "✂️", label: "Collage", category: "Arts & Crafts" },
  { icon: "💬", label: "Comic Art", category: "Arts & Crafts" },
  { icon: "🎨", label: "Graffiti & Murals", category: "Arts & Crafts" },
  { icon: "📄", label: "Origami", category: "Arts & Crafts" },
  { icon: "🕯️", label: "Candle Making", category: "Arts & Crafts" },
  { icon: "🧴", label: "Soap Making", category: "Arts & Crafts" },

  // Food
  { icon: "🍞", label: "Bread Baking", category: "Food" },
  { icon: "🥐", label: "Pastry & Desserts", category: "Food" },
  { icon: "🎂", label: "Cake Decorating", category: "Food" },
  { icon: "🍝", label: "Italian Cooking", category: "Food" },
  { icon: "🍣", label: "Japanese Cooking", category: "Food" },
  { icon: "🌮", label: "Mexican Cooking", category: "Food" },
  { icon: "🍛", label: "Indian Cooking", category: "Food" },
  { icon: "🥟", label: "Chinese Cooking", category: "Food" },
  { icon: "🥐", label: "French Cooking", category: "Food" },
  { icon: "🫒", label: "Mediterranean Cooking", category: "Food" },
  { icon: "🥦", label: "Vegan Cooking", category: "Food" },
  { icon: "🫙", label: "Fermentation", category: "Food" },
  { icon: "🍹", label: "Cocktail Making", category: "Food" },
  { icon: "☕", label: "Coffee Brewing", category: "Food" },
  { icon: "🍷", label: "Wine Tasting", category: "Food" },
  { icon: "🍺", label: "Beer Brewing", category: "Food" },
  { icon: "🔪", label: "Knife Skills", category: "Food" },
  { icon: "🥗", label: "Meal Prep", category: "Food" },
  { icon: "🍱", label: "Sushi Making", category: "Food" },
  { icon: "🔥", label: "BBQ & Grilling", category: "Food" },

  // Languages
  { icon: "🇪🇸", label: "Spanish", category: "Languages" },
  { icon: "🇫🇷", label: "French", category: "Languages" },
  { icon: "🇨🇳", label: "Mandarin", category: "Languages" },
  { icon: "🇯🇵", label: "Japanese", category: "Languages" },
  { icon: "🇧🇷", label: "Portuguese", category: "Languages" },
  { icon: "🇮🇹", label: "Italian", category: "Languages" },
  { icon: "🇩🇪", label: "German", category: "Languages" },
  { icon: "🇰🇷", label: "Korean", category: "Languages" },
  { icon: "🇸🇦", label: "Arabic", category: "Languages" },
  { icon: "🇷🇺", label: "Russian", category: "Languages" },
  { icon: "🇮🇳", label: "Hindi", category: "Languages" },
  { icon: "🇬🇷", label: "Greek", category: "Languages" },
  { icon: "🇳🇱", label: "Dutch", category: "Languages" },
  { icon: "🇵🇱", label: "Polish", category: "Languages" },
  { icon: "🇹🇷", label: "Turkish", category: "Languages" },
  { icon: "🇮🇱", label: "Hebrew", category: "Languages" },
  { icon: "🇻🇳", label: "Vietnamese", category: "Languages" },
  { icon: "🇹🇭", label: "Thai", category: "Languages" },
  { icon: "🇵🇭", label: "Tagalog", category: "Languages" },
  { icon: "🤟", label: "ASL", category: "Languages" },

  // Other
  { icon: "♟️", label: "Chess", category: "Other" },
  { icon: "🃏", label: "Poker Strategy", category: "Other" },
  { icon: "🪄", label: "Magic & Illusion", category: "Other" },
  { icon: "🎭", label: "Improv Comedy", category: "Other" },
  { icon: "🎤", label: "Stand-up Comedy", category: "Other" },
  { icon: "🎭", label: "Acting", category: "Other" },
  { icon: "📝", label: "Screenwriting", category: "Other" },
  { icon: "✍️", label: "Creative Writing", category: "Other" },
  { icon: "📰", label: "Journalism", category: "Other" },
  { icon: "🎙️", label: "Public Speaking", category: "Other" },
  { icon: "💬", label: "Debate", category: "Other" },
  { icon: "🧘", label: "Meditation", category: "Other" },
  { icon: "🌬️", label: "Breathwork", category: "Other" },
  { icon: "🌱", label: "Gardening", category: "Other" },
  { icon: "📈", label: "Investing & Finance", category: "Other" },
  { icon: "🏠", label: "Real Estate", category: "Other" },
  { icon: "💡", label: "Entrepreneurship", category: "Other" },
  { icon: "🛋️", label: "Interior Design", category: "Other" },
  { icon: "👗", label: "Fashion Styling", category: "Other" },
  { icon: "✂️", label: "Haircuts & Barbering", category: "Other" },
  { icon: "💅", label: "Nail Art", category: "Other" },
  { icon: "🪡", label: "Waxing & Threading", category: "Other" },
  { icon: "💄", label: "Makeup Artistry", category: "Other" },
  { icon: "🖊️", label: "Tattoo Art", category: "Other" },
  { icon: "🧴", label: "Skincare", category: "Other" },
  { icon: "🐾", label: "Pet Training", category: "Other" },
];

export const NEIGHBORHOODS = {
  Manhattan: [
    "Financial District", "Tribeca", "Chinatown", "Little Italy", "Lower East Side",
    "SoHo", "West Village", "Greenwich Village", "East Village", "Chelsea",
    "Flatiron", "Gramercy", "Murray Hill", "Hell's Kitchen", "Midtown",
    "Upper West Side", "Upper East Side", "Harlem", "East Harlem", "Washington Heights",
    "Inwood", "Morningside Heights", "Hamilton Heights",
  ],
  Brooklyn: [
    "Williamsburg", "Greenpoint", "DUMBO", "Brooklyn Heights", "Cobble Hill",
    "Carroll Gardens", "Red Hook", "Park Slope", "Prospect Heights", "Crown Heights",
    "Bed-Stuy", "Bushwick", "Ridgewood", "Flatbush", "Ditmas Park",
    "Sunset Park", "Bay Ridge", "Bensonhurst", "Coney Island", "Brighton Beach",
    "Sheepshead Bay", "Marine Park", "Canarsie", "East New York", "Brownsville",
    "Fort Greene", "Clinton Hill", "Gowanus", "Borough Park",
  ],
  Queens: [
    "Astoria", "Long Island City", "Sunnyside", "Woodside", "Jackson Heights",
    "Elmhurst", "Corona", "Flushing", "Forest Hills", "Rego Park",
    "Kew Gardens", "Jamaica", "Bayside", "Whitestone", "College Point",
    "Ridgewood", "Glendale", "Middle Village", "Maspeth", "Woodhaven",
    "Richmond Hill", "South Ozone Park", "Far Rockaway", "Howard Beach",
  ],
  Bronx: [
    "Riverdale", "Fieldston", "Kingsbridge", "Fordham", "Belmont",
    "Arthur Avenue", "Tremont", "Morrisania", "Mott Haven", "Port Morris",
    "Hunts Point", "Longwood", "Soundview", "Pelham Bay", "City Island",
    "Throggs Neck", "Co-op City", "Wakefield", "Woodlawn", "Norwood",
  ],
};

export function getBorough(neighborhood) {
  for (const [borough, neighborhoods] of Object.entries(NEIGHBORHOODS)) {
    if (neighborhoods.includes(neighborhood)) return borough;
  }
  return null;
}
