export const CATEGORIES = [
  "All",
  "Sports & Fitness",
  "Music",
  "Tech",
  "Arts & Crafts",
  "Food",
  "Languages",
  "Beauty & Style",
  "Performance & Stage",
  "Writing & Media",
  "Business & Money",
  "Home & Garden",
  "Wellness & Mind",
  "Games",
];

export const SKILLS = [
  // Sports & Fitness
  { icon: "🧘", label: "Yoga", category: "Sports & Fitness" },
  { icon: "🧘", label: "Pilates", category: "Sports & Fitness" },
  { icon: "🥊", label: "Boxing", category: "Sports & Fitness" },
  { icon: "🥋", label: "Muay Thai", category: "Sports & Fitness" },
  { icon: "🥋", label: "Brazilian Jiu-Jitsu", category: "Sports & Fitness" },
  { icon: "🥋", label: "Wrestling", category: "Sports & Fitness" },
  { icon: "🧗", label: "Rock Climbing", category: "Sports & Fitness" },
  { icon: "🏊", label: "Swimming", category: "Sports & Fitness" },
  { icon: "🏃", label: "Running", category: "Sports & Fitness" },
  { icon: "🚴", label: "Cycling", category: "Sports & Fitness" },
  { icon: "🏋️", label: "Weightlifting", category: "Sports & Fitness" },
  { icon: "🏋️", label: "CrossFit", category: "Sports & Fitness" },
  { icon: "🤸", label: "Gymnastics", category: "Sports & Fitness" },
  { icon: "🥋", label: "Martial Arts", category: "Sports & Fitness" },
  { icon: "🎾", label: "Tennis", category: "Sports & Fitness" },
  { icon: "🎾", label: "Squash", category: "Sports & Fitness" },
  { icon: "🏸", label: "Badminton", category: "Sports & Fitness" },
  { icon: "🏓", label: "Pickleball", category: "Sports & Fitness" },
  { icon: "⛳", label: "Golf", category: "Sports & Fitness" },
  { icon: "⚽", label: "Soccer", category: "Sports & Fitness" },
  { icon: "🏀", label: "Basketball", category: "Sports & Fitness" },
  { icon: "🏐", label: "Volleyball", category: "Sports & Fitness" },
  { icon: "🚣", label: "Rowing", category: "Sports & Fitness" },
  { icon: "🛹", label: "Skateboarding", category: "Sports & Fitness" },
  { icon: "💃", label: "Salsa", category: "Sports & Fitness" },
  { icon: "🕺", label: "Hip Hop Dance", category: "Sports & Fitness" },
  { icon: "💃", label: "Ballroom Dancing", category: "Sports & Fitness" },
  { icon: "🩰", label: "Ballet", category: "Sports & Fitness" },
  { icon: "🏃", label: "Parkour", category: "Sports & Fitness" },
  { icon: "💪", label: "Calisthenics", category: "Sports & Fitness" },
  { icon: "🧘", label: "Stretching & Mobility", category: "Sports & Fitness" },
  { icon: "🤺", label: "Fencing", category: "Sports & Fitness" },
  { icon: "🏹", label: "Archery", category: "Sports & Fitness" },
  { icon: "🏄", label: "Surfing", category: "Sports & Fitness" },
  { icon: "🏂", label: "Snowboarding", category: "Sports & Fitness" },
  { icon: "⛷️", label: "Skiing", category: "Sports & Fitness" },
  { icon: "🥾", label: "Hiking", category: "Sports & Fitness" },
  { icon: "🛶", label: "Kayaking", category: "Sports & Fitness" },
  { icon: "⛵", label: "Sailing", category: "Sports & Fitness" },
  { icon: "🐎", label: "Horse Riding", category: "Sports & Fitness" },
  { icon: "🏊", label: "Triathlon", category: "Sports & Fitness" },
  { icon: "🏃", label: "Marathon Training", category: "Sports & Fitness" },
  { icon: "🏋️", label: "Powerlifting", category: "Sports & Fitness" },
  { icon: "🏋️", label: "Olympic Weightlifting", category: "Sports & Fitness" },
  { icon: "📣", label: "Cheerleading", category: "Sports & Fitness" },
  { icon: "🤿", label: "Diving", category: "Sports & Fitness" },
  { icon: "🤽", label: "Water Polo", category: "Sports & Fitness" },
  { icon: "🏓", label: "Table Tennis", category: "Sports & Fitness" },
  { icon: "🥍", label: "Lacrosse", category: "Sports & Fitness" },
  { icon: "🏉", label: "Rugby", category: "Sports & Fitness" },
  { icon: "🏈", label: "Football", category: "Sports & Fitness" },
  { icon: "⚾", label: "Baseball", category: "Sports & Fitness" },
  { icon: "🥎", label: "Softball", category: "Sports & Fitness" },
  { icon: "🏏", label: "Cricket", category: "Sports & Fitness" },
  { icon: "🏑", label: "Field Hockey", category: "Sports & Fitness" },
  { icon: "⛸️", label: "Ice Skating", category: "Sports & Fitness" },
  { icon: "🏒", label: "Ice Hockey", category: "Sports & Fitness" },
  { icon: "🥌", label: "Curling", category: "Sports & Fitness" },

  // Music
  { icon: "🎸", label: "Acoustic Guitar", category: "Music" },
  { icon: "🎸", label: "Electric Guitar", category: "Music" },
  { icon: "🎸", label: "Bass Guitar", category: "Music" },
  { icon: "🎹", label: "Piano", category: "Music" },
  { icon: "🥁", label: "Drums", category: "Music" },
  { icon: "🎻", label: "Violin", category: "Music" },
  { icon: "🎻", label: "Viola", category: "Music" },
  { icon: "🎻", label: "Cello", category: "Music" },
  { icon: "🎺", label: "Trumpet", category: "Music" },
  { icon: "🎷", label: "Saxophone", category: "Music" },
  { icon: "🎵", label: "Flute", category: "Music" },
  { icon: "🎵", label: "Clarinet", category: "Music" },
  { icon: "🎵", label: "Trombone", category: "Music" },
  { icon: "🪕", label: "Ukulele", category: "Music" },
  { icon: "🪕", label: "Banjo", category: "Music" },
  { icon: "🪕", label: "Mandolin", category: "Music" },
  { icon: "🎤", label: "Classical Singing", category: "Music" },
  { icon: "🎤", label: "Pop Singing", category: "Music" },
  { icon: "🎤", label: "Beatboxing", category: "Music" },
  { icon: "🎛️", label: "Music Production", category: "Music" },
  { icon: "🎛️", label: "DJing", category: "Music" },
  { icon: "🎼", label: "Music Theory", category: "Music" },
  { icon: "✍️", label: "Songwriting", category: "Music" },
  { icon: "🎚️", label: "Sound Engineering", category: "Music" },
  { icon: "🎵", label: "Harp", category: "Music" },
  { icon: "🎵", label: "Oboe", category: "Music" },
  { icon: "🎺", label: "French Horn", category: "Music" },
  { icon: "🎺", label: "Tuba", category: "Music" },
  { icon: "🪘", label: "Marimba", category: "Music" },
  { icon: "🎹", label: "Synthesizer", category: "Music" },
  { icon: "🎤", label: "Choir & Choral", category: "Music" },
  { icon: "👂", label: "Ear Training", category: "Music" },
  { icon: "🎼", label: "Conducting", category: "Music" },
  { icon: "🎸", label: "Finger Picking", category: "Music" },
  { icon: "🎚️", label: "Loop Pedal Performance", category: "Music" },

  // Tech
  { icon: "🐍", label: "Python", category: "Tech" },
  { icon: "🌐", label: "JavaScript", category: "Tech" },
  { icon: "⚛️", label: "React", category: "Tech" },
  { icon: "🟢", label: "Node.js", category: "Tech" },
  { icon: "📱", label: "iOS Development", category: "Tech" },
  { icon: "📱", label: "Android Development", category: "Tech" },
  { icon: "🗄️", label: "SQL", category: "Tech" },
  { icon: "📊", label: "Data Science", category: "Tech" },
  { icon: "🤖", label: "Machine Learning", category: "Tech" },
  { icon: "🔒", label: "Cybersecurity", category: "Tech" },
  { icon: "🎨", label: "Web Design", category: "Tech" },
  { icon: "🖥️", label: "UX/UI Design", category: "Tech" },
  { icon: "⚙️", label: "DevOps", category: "Tech" },
  { icon: "🎮", label: "Game Development", category: "Tech" },
  { icon: "🎬", label: "Video Editing", category: "Tech" },
  { icon: "✨", label: "Motion Graphics", category: "Tech" },
  { icon: "🖨️", label: "3D Printing", category: "Tech" },
  { icon: "💬", label: "Prompt Engineering", category: "Tech" },
  { icon: "⛓️", label: "Blockchain", category: "Tech" },
  { icon: "🥽", label: "AR/VR Development", category: "Tech" },
  { icon: "🎬", label: "UI Animation", category: "Tech" },
  { icon: "📈", label: "Data Visualization", category: "Tech" },
  { icon: "📊", label: "Excel & Spreadsheets", category: "Tech" },
  { icon: "🔧", label: "No-Code Tools", category: "Tech" },
  { icon: "🔍", label: "SEO", category: "Tech" },
  { icon: "📱", label: "Digital Marketing", category: "Tech" },
  { icon: "🎙️", label: "Podcast Production", category: "Tech" },
  { icon: "🚁", label: "Drone Flying", category: "Tech" },

  // Arts & Crafts
  { icon: "✏️", label: "Drawing", category: "Arts & Crafts" },
  { icon: "🖌️", label: "Oil Painting", category: "Arts & Crafts" },
  { icon: "🎨", label: "Watercolor", category: "Arts & Crafts" },
  { icon: "🎨", label: "Acrylic Painting", category: "Arts & Crafts" },
  { icon: "✏️", label: "Illustration", category: "Arts & Crafts" },
  { icon: "🖨️", label: "Printmaking", category: "Arts & Crafts" },
  { icon: "🗿", label: "Sculpture", category: "Arts & Crafts" },
  { icon: "🏺", label: "Pottery & Ceramics", category: "Arts & Crafts" },
  { icon: "🧶", label: "Knitting", category: "Arts & Crafts" },
  { icon: "🧶", label: "Crocheting", category: "Arts & Crafts" },
  { icon: "🧵", label: "Sewing", category: "Arts & Crafts" },
  { icon: "🧵", label: "Embroidery", category: "Arts & Crafts" },
  { icon: "💍", label: "Jewelry Making", category: "Arts & Crafts" },
  { icon: "👜", label: "Leatherworking", category: "Arts & Crafts" },
  { icon: "🪚", label: "Woodworking", category: "Arts & Crafts" },
  { icon: "✒️", label: "Calligraphy", category: "Arts & Crafts" },
  { icon: "🖨️", label: "Screen Printing", category: "Arts & Crafts" },
  { icon: "📷", label: "Photography", category: "Arts & Crafts" },
  { icon: "📷", label: "Film Photography", category: "Arts & Crafts" },
  { icon: "✂️", label: "Collage", category: "Arts & Crafts" },
  { icon: "💬", label: "Comic Art", category: "Arts & Crafts" },
  { icon: "🎨", label: "Graffiti & Murals", category: "Arts & Crafts" },
  { icon: "📄", label: "Origami", category: "Arts & Crafts" },
  { icon: "🕯️", label: "Candle Making", category: "Arts & Crafts" },
  { icon: "🧴", label: "Soap Making", category: "Arts & Crafts" },
  { icon: "🧶", label: "Macrame", category: "Arts & Crafts" },
  { icon: "🧵", label: "Weaving", category: "Arts & Crafts" },
  { icon: "🎨", label: "Tie-Dye", category: "Arts & Crafts" },
  { icon: "🏺", label: "Glass Blowing", category: "Arts & Crafts" },
  { icon: "🎨", label: "Mosaic Art", category: "Arts & Crafts" },
  { icon: "🖥️", label: "Digital Art", category: "Arts & Crafts" },
  { icon: "🎨", label: "Sticker Design", category: "Arts & Crafts" },
  { icon: "🪑", label: "Furniture Restoration", category: "Arts & Crafts" },
  { icon: "📚", label: "Bookbinding", category: "Arts & Crafts" },
  { icon: "🪆", label: "Puppet Making", category: "Arts & Crafts" },
  { icon: "🌸", label: "Pressed Flower Art", category: "Arts & Crafts" },

  // Food
  { icon: "🍞", label: "Bread Baking", category: "Food" },
  { icon: "🥐", label: "Pastry & Desserts", category: "Food" },
  { icon: "🎂", label: "Cake Decorating", category: "Food" },
  { icon: "🍝", label: "Italian Cooking", category: "Food" },
  { icon: "🍣", label: "Japanese Cooking", category: "Food" },
  { icon: "🌮", label: "Mexican Cooking", category: "Food" },
  { icon: "🍛", label: "Indian Cooking", category: "Food" },
  { icon: "🥟", label: "Chinese Cooking", category: "Food" },
  { icon: "🥐", label: "French Cooking", category: "Food" },
  { icon: "🫒", label: "Mediterranean Cooking", category: "Food" },
  { icon: "🥦", label: "Vegan Cooking", category: "Food" },
  { icon: "🫙", label: "Fermentation", category: "Food" },
  { icon: "🍹", label: "Cocktail Making", category: "Food" },
  { icon: "☕", label: "Coffee Brewing", category: "Food" },
  { icon: "🍷", label: "Wine Tasting", category: "Food" },
  { icon: "🍺", label: "Beer Brewing", category: "Food" },
  { icon: "🔪", label: "Knife Skills", category: "Food" },
  { icon: "🥗", label: "Meal Prep", category: "Food" },
  { icon: "🍱", label: "Sushi Making", category: "Food" },
  { icon: "🔥", label: "BBQ & Grilling", category: "Food" },
  { icon: "🍜", label: "Thai Cooking", category: "Food" },
  { icon: "🍱", label: "Korean Cooking", category: "Food" },
  { icon: "🧆", label: "Middle Eastern Cooking", category: "Food" },
  { icon: "🥘", label: "Peruvian Cooking", category: "Food" },
  { icon: "🍲", label: "West African Cooking", category: "Food" },
  { icon: "🍞", label: "Sourdough", category: "Food" },
  { icon: "🧀", label: "Cheesemaking", category: "Food" },
  { icon: "🍫", label: "Chocolate Making", category: "Food" },
  { icon: "🍦", label: "Ice Cream Making", category: "Food" },
  { icon: "🍜", label: "Ramen Making", category: "Food" },
  { icon: "🥟", label: "Dumpling Making", category: "Food" },
  { icon: "🥟", label: "Dim Sum", category: "Food" },
  { icon: "🔥", label: "Smoking & Curing", category: "Food" },
  { icon: "📷", label: "Food Photography", category: "Food" },
  { icon: "🍄", label: "Foraging", category: "Food" },

  // Languages
  { icon: "🇪🇸", label: "Spanish", category: "Languages" },
  { icon: "🇫🇷", label: "French", category: "Languages" },
  { icon: "🇨🇳", label: "Mandarin", category: "Languages" },
  { icon: "🇯🇵", label: "Japanese", category: "Languages" },
  { icon: "🇧🇷", label: "Portuguese", category: "Languages" },
  { icon: "🇮🇹", label: "Italian", category: "Languages" },
  { icon: "🇩🇪", label: "German", category: "Languages" },
  { icon: "🇰🇷", label: "Korean", category: "Languages" },
  { icon: "🇸🇦", label: "Arabic", category: "Languages" },
  { icon: "🇷🇺", label: "Russian", category: "Languages" },
  { icon: "🇮🇳", label: "Hindi", category: "Languages" },
  { icon: "🇬🇷", label: "Greek", category: "Languages" },
  { icon: "🇳🇱", label: "Dutch", category: "Languages" },
  { icon: "🇵🇱", label: "Polish", category: "Languages" },
  { icon: "🇹🇷", label: "Turkish", category: "Languages" },
  { icon: "🇮🇱", label: "Hebrew", category: "Languages" },
  { icon: "🇻🇳", label: "Vietnamese", category: "Languages" },
  { icon: "🇹🇭", label: "Thai", category: "Languages" },
  { icon: "🇵🇭", label: "Tagalog", category: "Languages" },
  { icon: "🤟", label: "ASL", category: "Languages" },
  { icon: "🌍", label: "Swahili", category: "Languages" },
  { icon: "🇮🇷", label: "Farsi", category: "Languages" },
  { icon: "🇵🇰", label: "Urdu", category: "Languages" },
  { icon: "🇪🇸", label: "Catalan", category: "Languages" },
  { icon: "🇸🇪", label: "Swedish", category: "Languages" },
  { icon: "🇳🇴", label: "Norwegian", category: "Languages" },
  { icon: "🇫🇮", label: "Finnish", category: "Languages" },
  { icon: "🇩🇰", label: "Danish", category: "Languages" },
  { icon: "🇷🇴", label: "Romanian", category: "Languages" },
  { icon: "🇨🇿", label: "Czech", category: "Languages" },
  { icon: "🇭🇺", label: "Hungarian", category: "Languages" },
  { icon: "🌐", label: "Esperanto", category: "Languages" },

  // Beauty & Style
  { icon: "🧴", label: "Skincare", category: "Beauty & Style" },
  { icon: "✂️", label: "Haircuts & Barbering", category: "Beauty & Style" },
  { icon: "💅", label: "Nail Art", category: "Beauty & Style" },
  { icon: "💄", label: "Makeup Artistry", category: "Beauty & Style" },
  { icon: "🖊️", label: "Tattoo Art", category: "Beauty & Style" },
  { icon: "👗", label: "Fashion Styling", category: "Beauty & Style" },
  { icon: "🎨", label: "Hair Coloring", category: "Beauty & Style" },
  { icon: "💆", label: "Braiding & Loc Styling", category: "Beauty & Style" },
  { icon: "👒", label: "Wig Making", category: "Beauty & Style" },
  { icon: "🛍️", label: "Personal Shopping", category: "Beauty & Style" },
  { icon: "🛍️", label: "Vintage & Thrift Styling", category: "Beauty & Style" },
  { icon: "👁️", label: "Eyebrow Shaping", category: "Beauty & Style" },
  { icon: "🎭", label: "Special Effects Makeup", category: "Beauty & Style" },

  // Performance & Stage
  { icon: "🎭", label: "Improv Comedy", category: "Performance & Stage" },
  { icon: "🎤", label: "Stand-up Comedy", category: "Performance & Stage" },
  { icon: "🎭", label: "Acting", category: "Performance & Stage" },
  { icon: "🪄", label: "Magic & Illusion", category: "Performance & Stage" },
  { icon: "🎙️", label: "Public Speaking", category: "Performance & Stage" },
  { icon: "💬", label: "Debate", category: "Performance & Stage" },
  { icon: "🎤", label: "Spoken Word Poetry", category: "Performance & Stage" },
  { icon: "🤫", label: "Mime", category: "Performance & Stage" },
  { icon: "🪆", label: "Puppetry", category: "Performance & Stage" },
  { icon: "🤡", label: "Clowning", category: "Performance & Stage" },
  { icon: "🎭", label: "Musical Theatre", category: "Performance & Stage" },
  { icon: "🎤", label: "Voice Acting", category: "Performance & Stage" },
  { icon: "🎙️", label: "Hosting & Emceeing", category: "Performance & Stage" },
  { icon: "🎤", label: "Freestyle Rap", category: "Performance & Stage" },

  // Writing & Media
  { icon: "📝", label: "Screenwriting", category: "Writing & Media" },
  { icon: "✍️", label: "Creative Writing", category: "Writing & Media" },
  { icon: "📰", label: "Journalism", category: "Writing & Media" },
  { icon: "🎙️", label: "Podcasting", category: "Writing & Media" },
  { icon: "📖", label: "Storytelling", category: "Writing & Media" },
  { icon: "💻", label: "Blogging", category: "Writing & Media" },
  { icon: "📧", label: "Newsletter Writing", category: "Writing & Media" },
  { icon: "✍️", label: "Copywriting", category: "Writing & Media" },
  { icon: "📝", label: "Grant Writing", category: "Writing & Media" },
  { icon: "🖊️", label: "Poetry", category: "Writing & Media" },
  { icon: "🎭", label: "Playwriting", category: "Writing & Media" },
  { icon: "📚", label: "Children's Book Writing", category: "Writing & Media" },
  { icon: "📋", label: "Technical Writing", category: "Writing & Media" },
  { icon: "📱", label: "Social Media Content", category: "Writing & Media" },
  { icon: "🎬", label: "Documentary Making", category: "Writing & Media" },
  { icon: "📷", label: "Photography Editing", category: "Writing & Media" },
  { icon: "📹", label: "YouTube Content Creation", category: "Writing & Media" },

  // Business & Money
  { icon: "📈", label: "Investing & Finance", category: "Business & Money" },
  { icon: "🏠", label: "Real Estate", category: "Business & Money" },
  { icon: "💡", label: "Entrepreneurship", category: "Business & Money" },
  { icon: "✨", label: "Personal Branding", category: "Business & Money" },
  { icon: "🤝", label: "Negotiation", category: "Business & Money" },
  { icon: "💼", label: "Interview Prep", category: "Business & Money" },
  { icon: "📄", label: "Resume Writing", category: "Business & Money" },
  { icon: "🔗", label: "Networking", category: "Business & Money" },
  { icon: "📊", label: "Financial Modeling", category: "Business & Money" },
  { icon: "📈", label: "Stock Trading", category: "Business & Money" },
  { icon: "🪙", label: "Crypto", category: "Business & Money" },
  { icon: "📈", label: "Options Trading", category: "Business & Money" },
  { icon: "💰", label: "Tax Strategy", category: "Business & Money" },
  { icon: "📢", label: "Public Relations", category: "Business & Money" },
  { icon: "💰", label: "Fundraising", category: "Business & Money" },
  { icon: "📋", label: "Product Management", category: "Business & Money" },
  { icon: "📋", label: "Project Management", category: "Business & Money" },
  { icon: "💼", label: "Consulting", category: "Business & Money" },
  { icon: "📊", label: "Pitch Deck Design", category: "Business & Money" },

  // Home & Garden
  { icon: "🌱", label: "Gardening", category: "Home & Garden" },
  { icon: "🛋️", label: "Interior Design", category: "Home & Garden" },
  { icon: "🐾", label: "Pet Training", category: "Home & Garden" },
  { icon: "🔨", label: "Home Repair", category: "Home & Garden" },
  { icon: "🚗", label: "Car Maintenance", category: "Home & Garden" },
  { icon: "🐝", label: "Beekeeping", category: "Home & Garden" },
  { icon: "♻️", label: "Composting", category: "Home & Garden" },
  { icon: "🌿", label: "Hydroponics", category: "Home & Garden" },
  { icon: "🥬", label: "Urban Farming", category: "Home & Garden" },
  { icon: "⚡", label: "Electrical Basics", category: "Home & Garden" },
  { icon: "🔧", label: "Plumbing Basics", category: "Home & Garden" },
  { icon: "🧱", label: "Tiling & Flooring", category: "Home & Garden" },
  { icon: "🪑", label: "Furniture Making", category: "Home & Garden" },
  { icon: "🏠", label: "Smart Home Setup", category: "Home & Garden" },
  { icon: "🪴", label: "Houseplant Care", category: "Home & Garden" },
  { icon: "🧘", label: "Feng Shui", category: "Home & Garden" },

  // Wellness & Mind
  { icon: "🧘", label: "Meditation", category: "Wellness & Mind" },
  { icon: "🌬️", label: "Breathwork", category: "Wellness & Mind" },
  { icon: "🌿", label: "Mindfulness", category: "Wellness & Mind" },
  { icon: "🌟", label: "Life Coaching", category: "Wellness & Mind" },
  { icon: "😴", label: "Sleep Optimization", category: "Wellness & Mind" },
  { icon: "🧠", label: "Therapy & CBT Tools", category: "Wellness & Mind" },
  { icon: "🥗", label: "Nutrition & Dietetics", category: "Wellness & Mind" },
  { icon: "✅", label: "Habit Building", category: "Wellness & Mind" },
  { icon: "📚", label: "Stoicism", category: "Wellness & Mind" },
  { icon: "⭐", label: "Astrology", category: "Wellness & Mind" },
  { icon: "🃏", label: "Tarot Reading", category: "Wellness & Mind" },
  { icon: "🔔", label: "Sound Healing", category: "Wellness & Mind" },
  { icon: "✋", label: "Reiki", category: "Wellness & Mind" },
  { icon: "👐", label: "Acupressure", category: "Wellness & Mind" },
  { icon: "🧊", label: "Cold Therapy", category: "Wellness & Mind" },
  { icon: "⏱️", label: "Fasting & Longevity", category: "Wellness & Mind" },

  // Games
  { icon: "♟️", label: "Chess", category: "Games" },
  { icon: "🃏", label: "Poker Strategy", category: "Games" },
  { icon: "🎮", label: "Video Games", category: "Games" },
  { icon: "🎲", label: "Board Games", category: "Games" },
  { icon: "🐉", label: "Dungeons & Dragons", category: "Games" },
  { icon: "🃏", label: "Magic: The Gathering", category: "Games" },
  { icon: "🧩", label: "Speedcubing", category: "Games" },
  { icon: "❓", label: "Trivia & Quiz", category: "Games" },
  { icon: "🃏", label: "Poker", category: "Games" },
  { icon: "🃏", label: "Blackjack & Card Games", category: "Games" },
  { icon: "⚫", label: "Go", category: "Games" },
  { icon: "🎲", label: "Backgammon", category: "Games" },
  { icon: "⚔️", label: "Warhammer", category: "Games" },
  { icon: "🃏", label: "Yu-Gi-Oh", category: "Games" },
  { icon: "🕹️", label: "Competitive Gaming (Esports)", category: "Games" },
  { icon: "🎮", label: "Game Design", category: "Games" },
  { icon: "🔓", label: "Escape Room Design", category: "Games" },
  { icon: "🧩", label: "Puzzle Design", category: "Games" },
  { icon: "🕹️", label: "Arcade Games", category: "Games" },
  { icon: "🎯", label: "Darts", category: "Games" },
  { icon: "🎱", label: "Pool & Billiards", category: "Games" },
];

export const NEIGHBORHOODS = {
  Manhattan: [
    "Financial District", "Tribeca", "Chinatown", "Little Italy", "Lower East Side",
    "SoHo", "West Village", "Greenwich Village", "East Village", "Chelsea",
    "Flatiron", "Gramercy", "Murray Hill", "Hell's Kitchen", "Midtown",
    "Upper West Side", "Upper East Side", "Harlem", "East Harlem", "Washington Heights",
    "Inwood", "Morningside Heights", "Hamilton Heights",
  ],
  Brooklyn: [
    "Williamsburg", "Greenpoint", "DUMBO", "Brooklyn Heights", "Cobble Hill",
    "Carroll Gardens", "Red Hook", "Park Slope", "Prospect Heights", "Crown Heights",
    "Bed-Stuy", "Bushwick", "Ridgewood", "Flatbush", "Ditmas Park",
    "Sunset Park", "Bay Ridge", "Bensonhurst", "Coney Island", "Brighton Beach",
    "Sheepshead Bay", "Marine Park", "Canarsie", "East New York", "Brownsville",
    "Fort Greene", "Clinton Hill", "Gowanus", "Borough Park",
  ],
  Queens: [
    "Astoria", "Long Island City", "Sunnyside", "Woodside", "Jackson Heights",
    "Elmhurst", "Corona", "Flushing", "Forest Hills", "Rego Park",
    "Kew Gardens", "Jamaica", "Bayside", "Whitestone", "College Point",
    "Ridgewood", "Glendale", "Middle Village", "Maspeth", "Woodhaven",
    "Richmond Hill", "South Ozone Park", "Far Rockaway", "Howard Beach",
  ],
  Bronx: [
    "Riverdale", "Fieldston", "Kingsbridge", "Fordham", "Belmont",
    "Arthur Avenue", "Tremont", "Morrisania", "Mott Haven", "Port Morris",
    "Hunts Point", "Longwood", "Soundview", "Pelham Bay", "City Island",
    "Throggs Neck", "Co-op City", "Wakefield", "Woodlawn", "Norwood",
  ],
};

export function getBorough(neighborhood) {
  for (const [borough, neighborhoods] of Object.entries(NEIGHBORHOODS)) {
    if (neighborhoods.includes(neighborhood)) return borough;
  }
  return null;
}
